feat: tests for remote components
onecx/onecx-workspace-ui pull request #174
Opened 2024-05-23 06:52 UTC by markuczy

2024-05-23 07:33 UTC, anninowak requested changes
Hi Martin,
well done with the tests.
I have spotted only minor issues / suggestions. Reflect about it and decide if you want to incorporate theses changes or not.
Regarding one issue with the fixture, please align with Jan.

2024-05-23 07:33 UTC, anninowak commented on src/app/remotes/horizontal-main-menu/horizontal-main-menu.component.spec.ts
> +                name: 'Announcement & Help',
Suggestion: Announcement and Help

2024-05-23 07:33 UTC, anninowak commented on src/app/remotes/horizontal-main-menu/horizontal-main-menu.component.spec.ts
> +    expect(await menuItems[0].getText()).toEqual('Announcement & Help')
Suggestion: Announcement and Help

2024-05-23 07:33 UTC, anninowak commented on src/app/remotes/horizontal-main-menu/horizontal-main-menu.component.spec.ts
> +                  de: 'German welcome page'
Do you think it would make sense to use the german translation here?

2024-05-23 07:33 UTC, anninowak commented on src/app/remotes/horizontal-main-menu/horizontal-main-menu.component.spec.ts
> +  let fixture: ComponentFixture<OneCXHorizontalMainMenuComponent>
Please align with Jan regarding the fixture

2024-05-23 07:33 UTC, anninowak commented on src/app/remotes/user-sidebar-menu/user-sidebar-menu.harness.ts
> +  async expand() {
Suggestion: expandAccordion or expandXYZ

2024-05-23 07:33 UTC, anninowak commented on src/app/remotes/user-avatar-menu/user-avatar-menu.harness.ts
> +  async getButtonTitle(): Promise<string | null> {
Suggestion: Give more context information to the button
getUserAvatarButtonTitle (for example)

2024-05-23 07:33 UTC, anninowak commented on src/app/remotes/user-avatar-menu/user-avatar-menu.harness.ts
> +  getButton = this.locatorFor('#user-avatar-menu-button')
Suggestion: Give more context information to the button
getUserAvatarButton(for example)

2024-05-23 07:33 UTC, anninowak commented on src/app/remotes/user-avatar-menu/user-avatar-menu.harness.ts
> +  async getButtonTitle(): Promise<string | null> {
or getUserButton

2024-05-27 11:47 UTC, SchettlerKoehler approved these changes

2024-05-28 09:48 UTC, anninowak approved these changes

2024-05-28 10:42 UTC, SchettlerKoehler approved these changes

2024-05-28 11:38 UTC, merged